name: Deploy static content to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Build docs
        run: pnpm run docs:build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: packages/site/docs/.vitepress
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.LEON9916 }}
          publish_dir: ./packages/site/docs/.vitepress/dist
          cleanup: false
